import React from "react";
import Career from "@/app/career/components/Career";
import "@/app/career/components/Career.css";

export const metadata = {
  title: "Career | Expense Tracker",
  description: "Explore exciting career opportunities with us.",
  openGraph: {
    title: "Career | Expense Tracker",
    description: "Explore exciting career opportunities with us.",
    images: [
      {
        // 👇 Your OG image generated by: src/app/api/og/careerOg/route.js
        url: "https://expense-tracker-alpha-lyart.vercel.app/api/og/careerOg",
        width: 1200,
        height: 630,
      },
    ],
  },
};

export default function Page() {
  return (
    <div className="career-app">
      <Career />
    </div>
  );
}
